sudo: false
language: python
cache: pip

python:
  - 2.7
  - 3.6
  - 3.7

env:
  - DJANGO=1.8.14
  - DJANGO=1.11.17
  - DJANGO=2.1.8
  - DJANGO=2.2

install:
  - pip install Django==$DJANGO
  - python setup.py install
  - pip install -r dev-requirements.txt

script: coverage run test.py

after_success: bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: $PyPiLogin
  password: $PyPiPassword
  on:
    tags: true
